---
title: "Linking leaf spectra to the tree of life"
author: 
   - José Eduardo Meireles^[University of Maine], Jeannine Cavender-Bares^[University of Minnesota], and Brian O'Meara^[University of Tennessee]
date: \today{}
geometry: margin=2.5cm
fontsize: 12pt
header-includes:
    - \usepackage{setspace}
    - \doublespacing
output:
  pdf_document:
    toc: false
    toc_depth: 2
    number_sections: true
    fig_caption: true
bibliography: references.bib
biblio-style: authoryear
abstract:
    Evolutionary trees recount the history of how biological diversity came to be; giving rise to the incredible variation in plant form and function we see today. In this chapter, we will review what evolutionary trees (phylogenies) are and how to interpret them. We will then describe how to model the evolution of quantitative traits, discuss which evolutionary processes are involved, and familiarize ourselves with specific concepts and metrics – such as phylogenetic signal and evolutionary rates. Next, we will describe a framework that links phylogenies and leaf spectra by coupling models of evolution and radiative transfer models. We will discuss how spectra can help us understand leaf evolution and be used to detect biodiversity. Finally, we will review some of the challenges of subjecting spectra to evolutionary analyses.
---

# Introduction

Evolution is the engine behind the diversity in leaf structure and chemistry that is captured in their spectral profiles and, therefore, leaf spectra are inexorably linked to the tree of life. Our ability to distinguish species using spectra is a consequence of trait differences that arise and accumulate over evolutionary time. By the same token, the amount of variation that exists in certain spectral regions is determined by leaf attributes that are ultimately shaped by the interplay between different evolutionary processes. Even the degree to which an individual can respond to environmental change is rooted in evolution. There is an increasing interest in understanding leaf spectra through the lens of evolution and in the context of phylogenetic history. Advances on this front will require, however, a good understanding of how evolutionary biologists leverage the tree of life to make inferences about evolution.


# Evolutionary trees

## What are phylogenies and how to read them?

The idea that species descend from a common ancestor is at the very core of the theory of evolution. Evolutionary trees — or phylogenies — represent that branching structure of life, and describe how species are related to each other just like a genealogical tree recounts how people are related. Phylogenetic trees are composed of nodes, representing current organisms (tips) and their common ancestors (internal nodes), that are linked by branches that represent their relationships (\autoref{phylogeny_basics}). Lineages — or clades — are defined as a common ancestor and all of its descendents (\autoref{phylogeny_basics}{a}) and lineages that branch off from the same common ancestor are referred to as sisters. Relatedness among organisms is encoded in the phylogeny’s structure – it’s topology, which defines a series of lineages that are of hierarchically nested. The branch lengths can also convey information, such as the time since divergence, amount of molecular similarity, or number of generations (\autoref{phylogeny_basics}{a-b}). Usually, the distance between tip nodes and the order in which they are drawn has no meaning, but it can sometimes be used to display information about the trait values of a species (\autoref{phylogeny_basics}{c}). Because no one has been taking notes of how lineages split over the last 4 Billion years, phylogenetic trees must be estimated by analyzing current species data, generally DNA sequences, using models of evolution. Therefore, phylogenies are statistical inferences that have uncertainty about their structure and their branch lengths (\autoref{phylogeny_basics}{a,d}).

![**Phylogenetic trees depict the inferred evolutionary relationships between species.** **a.**
Clades (or lineages) are defined by a common ancestor and all of its descendants. All nodes – tips and ancestors alike – share a common ancestor at some point in time. The ancestral node from which all tree descends from is called the root. Confidence on the evolutionary relationships are show above internal branches. **b.** Branch lengths (here shown along the x-axis) may represent divergence times, number of generations or amount of molecular divergence (b). **c.** In some cases the y-axis is used to display information about a quantitative trait – such as leaf size – in a tree known as a phenogram or a traitigram. **d.** Unresolved relationships can be represented as three or more descendants stemming from the same ancestor, which is known as a polytomy. Uncertainty in divergence times are generally depicted with error bars at the internal nodes. \label{phylogeny_basics}](figures/phylogeny_basics.png)


## Why care about phylogenetic accuracy?

Phylogenetic inference depends on the accuracy of the reconstructed relationships between organisms. A phylogeny in which dandelions are more closely related to ferns than to roses tells us a very different story about the evolution of flowers than does a phylogeny in which all flowering plants belong to a single lineage. In other words, the accuracy of the estimated tree topology — the structure of the relationships between species — matters to how we understand evolution. Accurately inferring divergence times among species and lineages is also critical for making meaningful inferences about evolution. That is because, as we will see in the next section, our estimates about the pace of evolution of traits depends on the amount of change that occurs over a unit of time.
There are today several resources to help you generate a good phylogenetic tree for a set of species. 

A common approach is to trim the whole plant tree of life – taken from the Open Tree of Life [@Hinchliff2015-un] or Phylomatic [@Webb2005-eq], for example – to the set of species of interest. A second option is to reconstruct the phylogeny from scratch using DNA sequences and then time calibrating the tree using fossil information and molecular clock models. Tree reconstruction is a complex subject, making this is a tricky and laborious endeavor, but there are many tools that can help you through the process [@Pearse2013-dn]. Either way, cobbling a phylogenetic tree by sticking branches together by hand is unlikely to be the best route to take if you want to analyze your carefully-measured spectra.

Finally, as seen in the previous section, phylogenies are estimates and systematists have means of assessing uncertainty in their topology and their branch lengths, which are together referred to as phylogenetic uncertainty. For example, the divergence between two lineages may have a mean of 20 million years and a confidence interval or 95% highest posterior density of 18 to 22 million years. That uncertainty can (and should) be carried over to downstream statistical analyses.

# The evolution of quantitative traits

The study of evolution is fundamentally concerned with describing how organisms change through time and with understanding the processes driving change. Evolutionary change can be thought about at different taxonomic levels and temporal scales though, and the evolutionary processes under consideration are determined by our choice of scale. Because we are interested in understanding spectra in light of phylogenies, we will not discuss microevolutionary processes that occur at the population level such as genetic drift and natural selection. Instead, we will focus on describing how traits change across entire lineages over long timescales (usually millions of years), which is called macroevolution.

## Models of trait evolution at macroevolutionary scales: Brownian motion and Ornstein-Uhlenbeck

Macroevolutionary models of trait evolution ultimately describe the long–term consequences of short timescale evolution. At any point in time, a trait value can increase or decrease by a different amount due to mechanisms like selection, drift, and migration. For example, the reflectance of a spectral region may decrease due to selection for higher levels of a particular pigment; then increase due to a random change in leaf hair density, etc. Many such changes will occur over evolutionary time in each lineage. The pace at which those changes accumulate is at the core of what we call the rate of evolution. That rate can be different for different traits or between different lineages. Importantly, at a speciation event, the two descendant lineages start out with the same trait value and then diverge [@OMeara2006-uv].

Most models for evolution of quantitative traits leverage an idea from statistics known as the Central Limit Theorem, which states that the sum of many random changes leads to a normal distribution. Because trait evolution at macroevolutionary scales integrate over many random changes in trait values (due to varied processes), it may be described by a normal distribution. This model of evolution is known as Brownian motion (\autoref{example_evol_model}{a}, @OMeara2006-uv). In this model, the expected amount of variation in a trait depends on both the instantaneous rate of evolution and on the divergence time between species. This leads to a really important expectation; that trait values should be more similar among closely related taxa – which had little time to diverge – than among distantly related taxa.

With Brownian motion, an increase or decrease in a trait is equally likely, regardless of what the current value of a trait is. However, it could be more realistic to think of a trait being pulled towards some optimum (or, similarly but not quite the same, away from extreme values). This pull could be due to many processes: it is often considered to be pull towards some evolutionary optimum, but it could instead be a bias in mutation towards some value, repulsion from extremes, or other factors that lead to a pattern that grossly resembles a pull towards an optimum. The placement of the optimum, the strength of the pull, as well as the basic underlying rate of evolution are all parameters of this model, which is known as an Ornstein-Uhlenbeck process [@Butler2004-kx]. The degree of the pull towards the optimum is analogous to the strength of a rubber band linking the evolving trait on one end and the optimum trait value on the other end. A weak rubber band will provide enough slack for the trait to wiggle around the optimum (\autoref{example_evol_model}{b}) whereas a strong rubber band will keep the evolving trait close to the optimum (\autoref{example_evol_model}{c}). The strength of rubber band the also affects how quickly the trait is pulled towards is optimum (\autoref{example_evol_model}{b-c}). The time a trait is expected to take to get halfway to the optimum is called the phylogenetic half–life, and is an alternative way to think about the strength of the evolutionary pull.

![**Three independent realizations of the Brownian motion (BM) and Ornstein-Uhlenbeck (OU) processes.** **a.** In a BM model, trait values are equally likely to increase or decrease at each timestep.** b-c.** In contrast, traits in an OU model are more likely to move towards an optimum (represented by the red arrows). **b.** When the evolutionary pull is weak, traits move slowly towards their optimum. **c.** When the pull is strong, however, traits converge quickly to their optimum. \label{example_evol_model}](figures/example_evol_model.png)
 
Although traits vary within a species, populations and even within an individual. That variation may result from plastic responses to environmental conditions or have a genetic basis. 
Until recently, phylogenetic comparative methods ignored intraspecific variation and used species means instead. However, @Ives2007-kk and @Felsenstein2008-jh devised methods to account for within species variation, which typically enters the model as the standard-errors about the mean trait value of each species. 

## What does phylogenetic signal mean?

Phylogenetic signal can be thought as the degree to which of closely related species tend to resemble each other. Two different metrics have been widely used to assess phylogenetic signal: Pagel’s lambda [@Pagel1999-og] and Blomberg’s K [@Blomberg2003-bw]. Lambda is a scalar for the correlation between the phylogenetic similarity matrix and the trait matrix. It has the effect of shrinking the internal branches (as opposed to the terminal branches that lead to the tips) of a phylogeny, thereby reducing the expected species correlation due to shared evolutionary history (\autoref{mock_phylosig}{a-d}). A lambda value of 0 indicates that trait correlations between species are independent from evolutionary history whereas a lambda of 1 suggests that trait correlations are equal to the species correlation imposed by their shared evolutionary history assuming a Brownian motion model of evolution. Blomberg’s K measures the degree to which trait variance lies within clades versus among clades. Brownian motion is used as an expectation. K values greater than 1 indicate that that there is more variance among clades when expected by Brownian motion (\autoref{mock_phylosig}{e}) while K values smaller than 1 imply that more variance is found within clades than what is expected under a BM model (\autoref{mock_phylosig}{f}).

![**This is how phylogenetic signal is inferred.** **a–d** Pagel’s lambda is equivalent to scaling the internal branches of the phylogeny, which reduces the expected covariance between species due to evolutionary history. **e–f** Blomberg’s K measures phylogenetic signal by estimating the degree of variation between and within clades. **e.** K value is high when most trait variation is found between clades instead of within them  **f.** Conversely, K values are low when trait variation is mostly within clades.\label{mock_phylosig}](figures/mock_phylosig.png)

It is important to note that both Pagel’s Lambda and Blomberg’s K are tree wide metrics, meaning that they do not explicitly account for the heterogeneity among lineages. For example, an estimate of low phylogenetic signal in fruit shape across all flowering plants does not mean that fruits are not phylogenetically conserved within the oaks. Therefore, assessments of phylogenetic signal should be seen as indicators that are contingent on the scale of analysis and the particular species sampled instead of as general, hard truths.

It is also fundamental to realize that every time you calculate the phylogenetic signal of a trait, you are fitting an evolutionary model and buying into its assumptions. For example, most procedures to estimate phylogenetic signal using Blomberg’s K are based on a single rate Brownian motion model, and you are implicitly accepting the Brownian assumptions even if you do not know about it. 

# From the evolution of traits to spectra and back

Chemical and structural leaf attributes that underlie plant spectra evolve through time. Because leaf spectra integrate over these evolved leaf attributes, they can themselves carry information about phylogenetic relationships and about leaf evolution. If that is the case, how would one go about analyzing spectra in a phylogenetic context?

One approach is to subject the spectra directly to an evolutionary analysis, essentially assuming the spectrum to be a set of “traits”. For example, @McManus2016-vt estimated Pagel’s lambda on spectra from Amazonian plants, assuming each band to be an independent trait. @Cavender-Bares2016-si used PCA do reduce the dimensionality of the spectral data before estimating phylogenetic signal on the resulting principal component axes using Blomberg’s K. As insightful as this approach might be, the fact is that it is devoid of mechanism and does not allow us to verify that our inferences are biologically meaningful.

Another approach integrates phylogenies and leaf spectra (Meireles et al. in review, \autoref{framework}) by coupling the models of trait evolution described in the previous section with leaf radiative transfer models (\autoref{framework}) that predict spectral profiles from a small set of leaf attributes **(see the RTM Chapter)**. This framework explicitly posits that chemical and structural leaf attributes evolve and therefore, that the spectra that integrates over those traits carry the signature of evolution.  This approach describes that ancestral leaf traits have evolved over time along a phylogenetic tree, which is generally known. Traits can evolve according to different models of evolution, different rates, etc, and ultimately resulting the trait values we observe at the species or individual levels. Finally, those leaf traits underlie the spectra we measure.
This framework can be used in several ways. For example, we can simulate what leaf spectra would look like given a certain evolutionary model and phylogenetic tree (section 4.1). Alternatively, given a phylogeny and a spectral dataset, we can infer what ancestral spectra or ancestral traits were like if we assume a certain model of evolution. Finally, given a spectrum from an unknown plant we could estimate how it is related to other plants (section 4.3).

![**Framework integrating trait evolution and leaf spectral models that enables the estimation of evolutionary parameters from spectra and simulation of leaf spectra along a phylogeny**. Ancestral leaf attributes evolve along a phylogenetic tree under a given evolutionary regime, generating the current leaf attributes that underlie spectra. From the evolved leaf attributes, Radiative Transfer Models (RTMs) — such as PROSPECT — estimate spectra that carry the signature of the phylogeny.\label{framework}](figures/framework.png)


## Simulating leaf spectra under different evolutionary regimes

A model that describes the evolution of leaf spectra mediated by the evolution of leaf traits enables us to simulate spectral data in a phylogenetically explicit way. This allows us to forecast how different evolutionary scenarios would affect the shape and diversity of spectral profiles we observe. For example, (\autoref{sim_example_traitigram_and_spectra}) shows how the different scenarios for the evolution of leaf structure — the number of layers parameter (N) in PROSPECT5 — result in different amounts of trait variability. A fast Brownian rate (top left, \autoref{sim_example_traitigram_and_spectra}) results in higher trait variation than a slow Brownian rate (top center, \autoref{sim_example_traitigram_and_spectra}). Evolution under an Ornstein-Uhlenbeck model — which describes an evolutionary attraction towards the trait optimum — also results in less variation than the fast Brownian model even though their rates of evolution are the same. The trait values shaped by evolution have a noticeable effect on the spectral profiles of those lineages. 

![**Evolution of leaf structure under different evolutionary scenarios and their consequences to leaf spectra**. Top row depicts evolution according to an unbounded Brownian Motion model at two different rates and according to an Ornstein-Uhlenbeck process that models an evolutionary pull towards an optimum leaf structure value. The bottom row shows spectra estimated with the PROSPECT 5 model, where all leaf attributes evolved under the same model except for leaf structure, which evolved under the three scenarios outlined above.\label{sim_example_traitigram_and_spectra}](figures/sim_example_traitigram_and_spectra.png)


## Making evolutionary inferences from leaf spectra

Integrating spectra and phylogenies raises the exciting prospect of leveraging spectra to estimate aspects of the evolutionary process and test hypotheses. Some questions may be about evolutionary patterns in the spectra themselves. Those include investigations about phylogenetic signal or rates of evolution across the spectrum and there are a handful of studies that take this approach [@Cavender-Bares2016-si, @McManus2016-vt]. For example, Meireles et al. (in review) used a large spectral dataset for many species across the seed plant tree of life to ask how the phylogenetic signal varied across the leaf spectrum and across different phylogenetic groups (\autoref{empirical_phylosig}).

	Because we are often interested in biology, evolutionary inference made at the spectral level will often need to be interpreted a posteriori. For example, the signature of convergent evolution in this particular spectral band likely means that a certain trait X is evolutionarily convergent. An alternative approach is to infer traits from spectra first using either statistical (e.g. PLSR) or Radiative Transfer Model inversions (e.g. PROSPECT), and then study the evolution of those traits. 

![**Phylogenetic signal detected in leaf spectra varies across wavelengths and across the major lineages of seed plants**. **a.** Phylogenetic signal calculated using Blomberg's K (K) estimated for each major lineage of seed plants separately, where regions with significant signal (p-value < 0.05) are marked by colored circles with diameters proportional to K. **b.)) Mean spectra for each of the six major groups: gymnosperms (brown), Magnoliidae (green), monocots (red), non-core eudicots (purple), asterids (orange), and rosids (blue).\label{empirical_phylosig}](figures/empirical_phylosig.png)


Testing biological hypotheses is also possible because we can calculate the likelihood of our spectral data being generated by different models of evolution. Therefore, we can fit different evolutionary models that reflect our different hypotheses and compare them using a goodness of fit metric such as AIC [@Burnham2002-is]. We foresee innumerous interesting hypotheses being tested using this type of approach, especially related to evolutionary rates and convergent evolution.

Here is a mock but realistic example. We could hypothesize that plant lineages that shift from sunny to shade habitats see an increase in their leaf chlorophyll content from 20 ug/cm^2 to 60 ug/cm^2, that is, they have a new chlorophyll content optimum, and that should be reflected in their spectra (\autoref{ou_simulation_and_inference}{a-b}). We used the predictive approach established in the previous subsection to simulate leaf spectra under that evolutionary scenario. For visualization purposes, we show the difference between the “evolved” spectra and the ancestral spectrum in \autoref{ou_simulation_and_inference}{c}, which highlights the disparity in reflectance in the visible spectrum between sun and understory plants. We can then fit various models of evolution to the spectra (including one and two rate BM as well as a one optimum OU and two optimum OU, which is the true model), calculate their AIC, and compare models using AIC weights [@Burnham2002-is], as shown in \autoref{ou_simulation_and_inference}{d}.


![**Evolution of chlorophyll content under a multiple optima OU model.** **a-b.** Macroevolutionary shifts from sun exposed to understory habitats (a) result in chlorophyll content to be pulled towards different optima in different lineages (b). **c.** differences between the evolved spectra and the ancestral spectrum highlighting the effect of chlorophyll evolution on the visible region of the spectrum. **d.** we can use AIC to calculate how well various models of evolution, including the true multiple optima OU model, describe evolution across the spectrum. AIC weights suggest that the multiple optima OU model is preferred in the visible regions and nowhere else, which matches how the data were simulated.\label{ou_simulation_and_inference}](figures/ou_simulation_and_inference.png)


## Leaf spectra and biodiversity detection in an evolutionary context

Assessments of biodiversity based on leaf spectra have commonly focused on estimating species richness or doing species detection. Biodiversity is more than the number of species though; it encompasses, among other things, which branches of the tree of life are found in an area how much evolutionary history that represents. We can leverage the information about evolutionary history embedded in leaf spectral profiles to assess the diversity of lineages instead (or in addition to) the diversity in species or function. There are key conceptual advantages of taking this approach.

First, we can estimate lineage diversity at different phylogenetic scales when species level detection performs poorly. It is possible that classification models can detect broad clades more accurately that they could detect very young clades or species. For example, @Cavender-Bares2016-si found that leaf spectral information can more accurately identify broad oak clades (Kappa 0.81) than species (Kappa 0.61) and then population within a species (Kappa 0.34).

Second, we know that species definitions change over time and that many species in hyperdiverse ecosystems are still unknown to science. This begs the question; how do you classify something that you do not yet know about? Using evolutionary models to estimate where an unknown spectrum belongs on the tree of life bypasses the need for labeling, because is simply tells you who that unknown sample is likely related to, and still allows you to estimate phylogenetic diversity of site. This is possible because we can use the models of evolution described before to calculate the likelihood that the unknown spectrum belongs to different parts of the tree assuming that we know the correct evolutionary model and its parameter values. This is a lot to know (or assume), especially as go deeper in phylogenetic time and evolutionary history become more complex **(see section 5.2)**. 
	
# Cautionary notes

The integration of leaf spectra and phylogenies can provide breakthroughs in how we detect biodiversity, explain how spectral variation between species and lineages comes to be, and make inferences about the evolution of leaves. We should, nevertheless, be aware of the limitations inherent of making inferences about the deep past, be mindful of the sampling requirements and statistical assumptions of our analyses, and be careful to interpret our findings in a biologically meaningful way. Here are two important cautionary notes.

## Is your sampling adequate for making evolutionary inferences?

Inferences about the evolutionary process or that rely heavily on it — such as the degree of phylogenetic signal or the pace of evolution — are dependent on how well a lineage has been sampled. Evolutionary biologists usually target a particular lineage and strive to include in their analysis as many close relatives as possible regardless of their geographic location. Ecologists, on the other hand, tend to focus on a specific geographic area of interest and will end up sampling whatever species are there. This likely results in very severe undersampling of the total phylogenetic diversity that is represented by the particular species pool. Think about it: the 20 seed plants in your study site belong to a clade that has about 300,000 species, harbors incredible morphological and physiological diversity, and goes back 350 million years. Evolutionary analyses using this kind of sampling will very likely yield poor estimates of the evolutionary parameters: the species in your area can tolerate a subset of all the climate conditions other seed plants can handle, for example. 

In addition, ecological processes themselves can lead to bias in estimates of evolutionary parameters. For example, extremely arid conditions may act as an environmental filter that curbs colonization by species with low leaf water content, thus reducing the amount of variability in leaf succulence. As a consequence, estimates of the rate of evolution of leaf succulence based on species found in that hyper arid community may be artificially low.

These caveats should be kept in mind when analyzing spectra in an evolutionary context. Finding that certain spectral regions have high phylogenetic signal in a large forest plot does not necessarily mean that those regions are truly phylogenetically conserved.

## The more of the tree of life you sample, the more complex models will (or should) be.

Most of the models of evolution and phylogenetic signal statistics we saw here are actually rather simple. For example, a Brownian motion (BM) model has two parameters, the trait value at the root (mean) and the rate of evolution (variance). The single rate BM model may reasonably describe the evolution of leaf water content in dogwoods (Cornus), but it would probably do a terrible job if you were analyzing all flowering plants because of the sheer heterogeneity and diversity that they possess [@Felsenstein2008-jh, @OMeara2012-rs, @Cornwell2014-el].

There is a tradeoff: the most realistic model would have a different set of parameters at every time point on every branch but would have far more parameters to estimate than the data could support; a simple model of one set of parameters across all the time periods and species examined is clearly unrealistic. Most applications have used the simplest approach, but there are ways to allow for more complex models. Some of these test a priori hypotheses about heterogeneity in models of evolution: biologists propose particular models linking sets of parameters on different parts of the tree (gymnosperms and angiosperms having different rates of evolution, for example, versus a mapping with them all having the same rate) and then the methods select between the possible models [@Butler2004-kx, @OMeara2006-uv]. There are also methods that can automatically search across possible mappings to find the ones that fit best [@Uyeda2014-rc]. In the case of multiple characters, such as reflectance at different wavelengths of light, there is also the question of whether different characters are evolving under the same or different models, and there are models to test that, as well [@Adams2013-zm].

Early attempts to analyze spectra in an evolutionary context (@Cavender-Bares2016-si, @McManus2016-vt, Meireles et al. in review) have used models that are maximally simple for each character (a single model applying for all taxa and times) are nearly maximally complex  between characters (each trait evolves independently of all others on the same common tree). Those approaches are computationally cheap but are at odds with our understanding of biology (i.e. models of evolution do vary among lineages) and physics (i.e. spectral bands do covary). Other ways of segregating complexity, such as models that incorporate heterogeneity among lineages and account for the covariance among spectral bands remain potentially more fruitful ways of examining the diversity in leaf spectra.

## Spectra do not evolve*, leaves do!

{*unless when they do}.

One could estimate the pace of evolution of the beaks of Darwin's finches from their photographs. But the photographs didn’t evolve. Leaf spectra do capture many different aspects of the complex phenotype and, we have seen in this chapter, each band of a spectrum can be analysed as a trait in an evolutionary model. This does not necessarily mean that spectra themselves are traits nor that they themselves evolve. For example, there is no reason for evolution to favor lower reflectance at 660 nm. However, there may be biological reasons for natural selection to favor higher amounts of Chlorophyll a in a leaf, which happens to absorb light at 660 nm. Terminology such as “evolution of spectra” or “spectral niches” may be efficient communication shortcuts but can also cause confusion. They may make it all to easy lose sight of the biological mechanisms behind the observed phenomena.

Advances in analyzing spectral data in light of evolution will require keeping mechanisms in mind. Having said that, phylogenetic inference on spectra can be used as a discovery tool. Consistently finding high rates evolution in a spectral region not associated with a known function should trigger further investigation. Moreover, mechanistic thinking may end up proving us wrong and show that spectra in fact evolve (at least some regions). For example, increased leaf reflectance that prevents leaf overheating could be favored by evolution. Sure, high reflectance results from “real” traits — such as bright hairs, cuticles, and waxes —  but one can argue that there is biological meaning in the evolution of reflectance itself in this case.

## Ignore phylogeny at your peril

Phylogeny adds complexity to an analysis, but has benefits in new insights (estimating ancestral leaf spectra, helping to go from observations to traits, and more). However, it can be tempting to analyze data on multiple species without incorporating this. The problem with this is many methods that do that, for example, partial least squares regression that estimate traits from spectra, assume species are independent data points. They are not. There is thus the risk of “overcounting” some species: for example, if one wants to develop a model for all plants, and one has five oak species, a gingko, a pine, and a magnolia, the final model will essentially be an oak mode with some deviations. However, the five oaks have shared much of their evolutionary history and so do not represent five independent instances of evolution. Phylogenies can be included into such analyses, and their importance appropriately scaled (in some cases, they will not affect results, but this is only knowable once the tree is used), and make results far more robust.


# References
